# Permalinks
permalink:           pretty

# Setup
title:               Steno for Mere Mortals
tagline:             ''
description:         ''
url:                 https://www.stenoformeremortals.com
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Jim Ladd
  url:               https://twitter.com/jladdjr
  email:             jladdjr@gmail.com

# Custom vars
version:             0.0.1
