# Permalinks
permalink:           pretty

# Setup
title:               Jim Ladd's B(inary) Log
tagline:             'Steno, Ham Radio, this and that..'
description:         'Steno, Ham Radio, this and that..'
url:                 https://jladdjr.github.io
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Jim Ladd
  url:               https://twitter.com/jladdjr
  email:             jladdjr@gmail.com

# Custom vars
version:             0.0.1
