# Permalinks
permalink:           pretty

# Setup
title:               Jim Ladd's blog
tagline:             'New blog'
description:         'Working on structure of blog atm..'
url:                 https://jladdjr.github.io
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Jim Ladd
  url:               https://twitter.com/jladdjr
  email:             jladdjr@gmail.com

# Custom vars
version:             1.0.2
